/**
EXAMPLE USAGE OF ALGORITHMS
*/
SELECT LEN('THE QUICK BROWN FOX'),LEN('THE QUICK FOX'), LEN('THE QUICK FOX')*1.0/LEN('THE QUICK BROWN FOX')


SELECT 'LEVENSHTEIN' AS ALGORITHM,SIMILARITY_001_00.Levenshtein('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'BLOCK DISTANCE' AS ALGORITHM,SIMILARITY_001_00.BlockDistance('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'ChapmanLengthDeviation' AS ALGORITHM,SIMILARITY_001_00.ChapmanLengthDeviation('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'CosineSimilarity' AS ALGORITHM,SIMILARITY_001_00.CosineSimilarity('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'DiceSimilarity' AS ALGORITHM,SIMILARITY_001_00.DiceSimilarity('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'EuclideanDistance' AS ALGORITHM,SIMILARITY_001_00.EuclideanDistance('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'JaccardSimilarity' AS ALGORITHM,SIMILARITY_001_00.JaccardSimilarity('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'Jaro' AS ALGORITHM,SIMILARITY_001_00.Jaro('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'JaroWinkler' AS ALGORITHM,SIMILARITY_001_00.JaroWinkler('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'Levenshtein' AS ALGORITHM,SIMILARITY_001_00.Levenshtein('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'MatchingCoefficient' AS ALGORITHM,SIMILARITY_001_00.MatchingCoefficient('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'MongeElkan' AS ALGORITHM,SIMILARITY_001_00.MongeElkan('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'NeedlemanWunch' AS ALGORITHM,SIMILARITY_001_00.NeedlemanWunch('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'OverlapCoefficient' AS ALGORITHM,SIMILARITY_001_00.OverlapCoefficient('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'QGramsDistance' AS ALGORITHM,SIMILARITY_001_00.QGramsDistance('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'SmithWaterman' AS ALGORITHM,SIMILARITY_001_00.SmithWaterman('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'SmithWatermanGotoh' AS ALGORITHM,SIMILARITY_001_00.SmithWatermanGotoh('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'SmithWatermanGotohWindowedAffine' AS ALGORITHM,SIMILARITY_001_00.SmithWatermanGotohWindowedAffine('THE QUICK BROWN FOX','THE QUICK FOX')



