/**
EXAMPLE USAGE OF ALGORITHMS
*/
SELECT LEN('THE QUICK BROWN FOX'),LEN('THE QUICK FOX'), LEN('THE QUICK FOX')*1.0/LEN('THE QUICK BROWN FOX')


SELECT 'LEVENSHTEIN' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.Levenshtein('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'BLOCK DISTANCE' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.BlockDistance('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'ChapmanLengthDeviation' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.ChapmanLengthDeviation('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'CosineSimilarity' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.CosineSimilarity('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'DiceSimilarity' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.DiceSimilarity('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'EuclideanDistance' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.EuclideanDistance('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'JaccardSimilarity' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.JaccardSimilarity('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'Jaro' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.Jaro('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'JaroWinkler' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.JaroWinkler('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'Levenshtein' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.Levenshtein('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'MatchingCoefficient' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.MatchingCoefficient('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'MongeElkan' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.MongeElkan('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'NeedlemanWunch' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.NeedlemanWunch('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'OverlapCoefficient' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.OverlapCoefficient('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'QGramsDistance' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.QGramsDistance('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'SmithWaterman' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.SmithWaterman('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'SmithWatermanGotoh' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.SmithWatermanGotoh('THE QUICK BROWN FOX','THE QUICK FOX')
UNION ALL
SELECT 'SmithWatermanGotohWindowedAffine' AS ALGORITHM,SIMILARITY_@MAJOR.VERSION@_@MINOR.VERSION@_@PATCH.VERSION@.SmithWatermanGotohWindowedAffine('THE QUICK BROWN FOX','THE QUICK FOX')



