IF OBJECT_ID('tempdb..#ADDRESSES') IS NOT NULL
    DROP TABLE #ADDRESSES

create table #ADDRESSES
(
	ID		INT
	,[ADDRESS] nvarchar(max)
)

insert into #ADDRESSES (ID,[ADDRESS])
VALUES 
( 1,'10 MAIN STREET')
,( 2,'33 LOWER MAIN STREET')
,( 3,'LONDON CITY')



SELECT 
*
,SIMILARITY_001.Levenshtein(A.ADDRESS,B.ADDRESS)	AS LEVENSHTEIN
,SIMILARITY_001.JaroWinkler(A.ADDRESS,B.ADDRESS)	AS JAROWINKLER
FROM #ADDRESSES A
CROSS JOIN
#ADDRESSES B
WHERE A.ID<>B.ID
ORDER BY A.ID, B.ID
